FROM golang:alpine as builder

WORKDIR /code

RUN apk add --no-cache git

RUN git clone https://github.com/xteve-project/xTeVe.git

RUN go get github.com/koron/go-ssdp
RUN go get github.com/gorilla/websocket
RUN go get github.com/kardianos/osext

RUN mkdir /out

RUN CGO_ENABLED=0 GOOS=linux GOARCH=arm GOARM=7 go build -o /out/xteve.go

FROM scratch as runtime

WORKDIR /app
COPY --from=builder /out .

EXPOSE 34400

ENTRYPOINT ["/app/xteve.go"]